# Generated by Django 5.0.6 on 2024-06-29 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_name_event_title_alter_event_attendees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_Planner',
            field=models.ForeignKey(limit_choices_to={'role': 'event_planner'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.DeleteModel(
            name='Event_Planner',
        ),
    ]
