# Generated by Django 5.0.6 on 2024-06-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_event_planner_remove_event_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendee_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
