# Generated by Django 5.0.6 on 2024-06-18 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendees', '0002_alter_registration_name'),
        ('events', '0001_initial'),
        ('reviews_feedbacks', '0001_initial'),
        ('vendors', '0003_vendor_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_generated_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews_feedbacks.review')),
                ('total_attendees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.IntegerField()),
                ('report_generated_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Performance_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_event_served', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('report_generated_date', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
