# Generated by Django 5.0.4 on 2024-06-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='service_offered',
        ),
        migrations.AddField(
            model_name='vendor',
            name='service_offered',
            field=models.ManyToManyField(related_name='vendors', to='vendors.service'),
        ),
    ]
