# Generated by Django 5.0.6 on 2024-06-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendor_service_offered_vendor_service_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
