# Generated by Django 5.0.6 on 2024-06-29 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendor_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='assigned_Event',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='event_datetime',
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(default=1, limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
