# Generated by Django 5.0.6 on 2024-06-18 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.attendee'),
        ),
    ]
